# DO NOT EDIT THIS FILE - it gets automatically generated by running "bin/parse-rules"

CUSTOM_BOTS_RULES = [{:app=>"curl", :match=>{"regex"=>"^Faraday"}, :platform=>"bot", :test=>{"userAgents"=>[{"userAgent"=>"Faraday v1.0.1"}]}}, {:app=>"curl", :match=>{"regex"=>"like curl"}, :platform=>"bot", :test=>{"userAgents"=>[{"userAgent"=>"Faraday for Podigee (like curl)"}]}}].freeze